---
title: "**Global Violence**"
author: "My An Huynh, Jeffrey Lin, Soo Min You, Hyun Kim, Malika Top"
output: 
  html_document:
    toc: true
    toc_float: true
---

# *Screencast*

<iframe width="560" height="315" src="https://www.youtube.com/watch?v=aonZgOBF3fQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

# *Motivation*

Globally, violence undermines social and economic development, with its impacts 
being more pronounced in "developing" countries. Communities lacking adequate 
resources or experiencing systemic inequities are more vulnerable to various 
health challenges, including violence. Factors that influence health also play 
a role in shaping violence, which in turn affects determinants such as housing, 
education, transportation, and economic conditions. This project seeks to 
explore the factors driving serious assault, sexual violence, and intentional 
homicide worldwide from 2015 to 2023. 

We selected this time frame because it includes significant global events, 
including the COVID-19 pandemic and various conflicts, which have greatly 
influenced patterns of violence. Furthermore, even though there was a lot of missing 
data for 2023, we ultimately decided to include it in our analysis because of the
conflicts that defined this year. 

# *Related Work*

Conflict trends in 2023 revealed increasing threats to the state of global peace. 
New York Times (NYT) Journalist, Marc Lacey, titled NYT’s annual photojournalism 
review [“A Weary World”](https://www.nytimes.com/interactive/2023/world/year-in-pictures.html). 
Though 2024 comes to a close, the conflicts in Russia, Gaza, Ethiopia, and 
Sudan rage on, and more understanding of violence trends is needed. Tensions 
within and across countries have major implications for not just conflict 
prevention but also social and economic preservation which are often more fragile 
in vulnerable areas.

# *Initial Questions*

1. How can we best predict violence and homicide rates (i.e. what are its indicators)? 
2. How do rates of indicators compare across global regions and countries? 
3. How do rates of violence and homicide compare across global and regions and countries?
4. What categories of violence are most prevalent? 