---
title: "P8105 Final Project Proposal: Determinants of Global Violence"
output: github_document
---

### Members

My An Huynh (mh4589), Jeffrey Lin (jl7035), Soo Min You (sy3269), Hyun Kim 
(hk3373), Malika Top (mt3775)

### Motivation

Across the world, violence compromises social and economic development, with 
effects felt more in countries categorized as “developing”.  Communities living 
without adequate resources and those facing unfair treatment are more 
susceptible to all health issues, including violence. The factors that enhance 
or inhibit health also impact violence, while violence in turn affects 
determinants such as housing, education, transportation, and economic 
conditions. In this project, we aim to better understand the determinants of 
serious assault, sexual violence, and intentional homicide across the globe 
from 2015-2023.   

### Intended Final Product

For our final product, we intend to deliver a comprehensive final report and a 
website built using Shiny with an introductory landing page, pages for 
exploratory data analysis and linear models. 

### Anticipated Data Sources

Since we are exploring the various determinants of global violence, we have 
chosen the United Nations Office on Drugs and Crime (UNODC) database 
(https://dataunodc.un.org/) to be our primary data source, which includes key 
indicators and data of violence. We will also be using the World Bank Dataset 
to include socioeconomic indicators. 

### Planned Analyses/Visualizations/Coding Challenges 

* Analyses: multiple linear regression and k-means clustering on indicators of 
violence.
* Visualizations: Map of prevalence of certain violence outcomes, scatter plots 
between the several independent variables and each outcome variable of interest, 
violin plots or boxplots for each outcome variable, grouping by geographic 
region.
* Coding challenges: data quality issues such as missing data based on region, 
year and variable of interest. Differing reporting methodologies among countries 
may also influence the validity of our analysis. 

### Planned Timeline

* Week of 11/11 - 11/17: Data importing and cleaning, zoom meeting with 
teaching team member
* Week of 11/18 - 11/24: Exploratory data analysis and visualization 
* Week of 11/25 - 12/1: Webpage development, organization of EDA and 
visualization
* Week of 12/2 - 12/9: Report, screencast and peer assessment 

