<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="My An Huynh, Jeffrey Lin, Soo Min You, Hyun Kim, Malika Top" />


<title>P8105 Final Project: Determinants of Global Violence</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="data_cleaning.html">Data Cleaning</a>
</li>
<li>
  <a href="eda.html">EDA</a>
</li>
<li>
  <a href="regression.html">Regression</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Shiny &amp; Dashboard
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://yousmni3269.shinyapps.io/shiny_prevalence/">Prevalence of Violence</a>
    </li>
    <li>
      <a href="https://yousmni3269.shinyapps.io/shiny_trend/">Trends of Violence</a>
    </li>
    <li>
      <a href="plotly_vs.html">Homicide vs. Violence</a>
    </li>
  </ul>
</li>
<li>
  <a href="p8105_fp_report.html">Project Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="aboutus.html">About Us</a>
</li>
<li>
  <a href="https://github.com/projecthyee/globalviolence">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore"><strong>P8105 Final Project: Determinants
of Global Violence</strong></h1>
<h4 class="author">My An Huynh, Jeffrey Lin, Soo Min You, Hyun Kim,
Malika Top</h4>

</div>


<div id="motivation" class="section level1">
<h1><em>Motivation</em></h1>
<p>Globally, violence undermines social and economic development, with
its impacts being more pronounced in “developing” countries. Communities
lacking adequate resources or experiencing systemic inequities are more
vulnerable to various health challenges, including violence. Factors
that influence health also play a role in shaping violence, which in
turn affects determinants such as housing, education, transportation,
and economic conditions. This project seeks to explore the factors
driving serious assault, sexual violence, and intentional homicide
worldwide from 2015 to 2023.</p>
<p>Selected this time frame because it includes significant global
events, including the COVID-19 pandemic and various conflicts, which
have greatly influenced patterns of violence. Also, even though there
are a lot of missing data for year 2023, we decided to include the year
because this time period provides insight into the contemporary factors
shaping violence worldwide.</p>
</div>
<div id="related-work" class="section level1">
<h1><em>Related Work</em></h1>
<p>Conflict trends in 2023 revealed increasing threats to the state of
global peace. New York Times (NYT) Journalist, Marc Lacey, titled NYT’s
annual photojournalism review <a
href="https://www.nytimes.com/interactive/2023/world/year-in-pictures.html">“A
Weary World”</a>. Though 2024 comes to a close , the conflicts in
Russia, Gaza, Ethiopia, and Sudan rage on, and more understanding of
violence trends is needed. Tensions within and across countries have
major implications for not just conflict prevention but also social and
economic preservation which are often more fragile in vulnerable
areas.</p>
</div>
<div id="initial-questions" class="section level1">
<h1><em>Initial Questions</em></h1>
<ol style="list-style-type: decimal">
<li>How can we best predict violence and homicide rates (i.e. what are
its indicators)?</li>
<li>How do rates of indicators compare across global regions and
countries?</li>
<li>How do rates of violence and homicide compare across global and
regions and countries?</li>
<li>What categories of violent are most prevalent?</li>
</ol>
</div>
<div id="data" class="section level1">
<h1><em>Data</em></h1>
<div id="source" class="section level2">
<h2>Source</h2>
<p>Since there are many determinants and indicators of violence, we
chose the indicators and outcomes that seem most relevant and
interesting in exploring violence from the following sources:</p>
<ul>
<li>United Nations Development Program (UNDP):
<ul>
<li>Human Development Index</li>
</ul></li>
<li>United Nations Office of Drugs and Crime (UNODC)
<ul>
<li>Corruption and Economic Crime</li>
<li>Criminal Justice Personnel</li>
<li>Human Trafficking</li>
<li>Intentional Homicide</li>
<li>Violent and Sexual Crimes</li>
</ul></li>
<li>World Bank
<ul>
<li>Gross Domestic Product (GDP)</li>
<li>Inflation Rate (Measured by Consumer Price Index)</li>
<li>Unemployment Rate</li>
</ul></li>
<li>World Health Organization (WHO)
<ul>
<li>Alcohol Consumption</li>
</ul></li>
</ul>
<p>Intentional homicide, and violent and sexual crimes were chosen as
the outcome variable to quantify violence.</p>
<ul>
<li>Intentional homicide:
<ul>
<li>counting unit: number of homicide victims per 100,000
population</li>
<li>classification:
<ul>
<li>situational context: organized crime, interpersonal (excluding
familial/intimate), socio-political</li>
<li>relationship to perpetrator: intimate partner, family member,
friend, colleague, etc.</li>
<li>mechanism: firearm, weapon, physical force</li>
</ul></li>
</ul></li>
<li>Violent and sexual crimes:
<ul>
<li>counting unit: number of individual offences per 100,000
population</li>
<li>classification of offenses:
<ul>
<li>rape</li>
<li>serious assault</li>
<li>kidnapping</li>
<li>sexual violence</li>
</ul></li>
<li>NOTE: some countries used other counting unit (a series of offenses
to form a case, or multiple cases to form an investigation)</li>
</ul></li>
</ul>
</div>
<div id="scraping-method" class="section level2">
<h2>Scraping Method</h2>
<p>The datasets were downloaded from the official websites of the
sources above. The names of the files were also changed accordingly for
clarity and to avoid confusion. For example, the alcohol consumption
data file was renamed from “data.csv” to “alcohol_consumption.csv”.</p>
</div>
<div id="tidy-eda-data" class="section level2">
<h2>Tidy EDA Data</h2>
<p>For EDA, since we are interested in exploring the trends of global
violence, we imported and tidied the datasets for our two outcome
variables: homicide and violence.</p>
<div id="homicide-dataset" class="section level3">
<h3>Homicide Dataset</h3>
<pre class="r"><code>homicide_visual_df = 
    read_excel(path = &quot;data/unodc/intentional_homicide.xlsx&quot;,
               skip = 2) |&gt;
  janitor::clean_names() |&gt;
  filter(unit_of_measurement == &quot;Rate per 100,000 population&quot;,
         indicator == &quot;Victims of intentional homicide&quot;,
         category != &quot;Total&quot;,
         sex != &quot;Total&quot;,
         between(year, 2015, 2023)) |&gt;
  select(country, region, category, sex, year, 
         homicide_rate = value) |&gt;
  mutate(category = str_replace_all(category, 
                                    &quot;^Intimate partner or family member.*&quot;, 
                                    &quot;Intimate partner or family member&quot;),
         category = str_replace_all(category, 
                                    &quot;^Socio-political homicide.*&quot;, 
                                    &quot;Socio-political homicide&quot;))

write.csv(homicide_visual_df, file = &quot;./data/homicide_visual.csv&quot;)</code></pre>
<p>The tidied homicide dataset includes country, region, category of
homicide victims, sex, year and victim rate of homicide. The dataset
included data for both counts and rates per 100,000 people. Therefore,
we filtered to choose rates per 100,000 people since it allows
standardization for comparability by adjusting for differences in
population size.</p>
</div>
<div id="violence-dataset" class="section level3">
<h3>Violence Dataset</h3>
<pre class="r"><code>violence_visual_df = 
    read_excel(path = &quot;data/unodc/violent_sexual_crime.xlsx&quot;,
               skip = 2) |&gt;
  janitor::clean_names() |&gt;
  filter(unit_of_measurement == &quot;Rate per 100,000 population&quot;,
         between(year, 2015, 2023)) |&gt;
  select(country, region, indicator, category, sex, year, 
         violence_rate = value) |&gt;
  mutate(category = str_replace_all(category, 
                                    &quot;^Sexual violence.*&quot;, 
                                    &quot;Sexual violence&quot;))

write.csv(violence_visual_df, file = &quot;./data/violence_visual.csv&quot;)</code></pre>
<p>The tidied violence dataset includes country, region, indicator,
category of violence, sex, year and violence rate. The indicator
includes different rates for violence (violent offences and victims)
which are explored further in EDA. Rates per 100,000 people were chosen
also for this dataset for comparability.</p>
</div>
</div>
<div id="tidy-regression-data" class="section level2">
<h2>Tidy Regression Data</h2>
<p>For regression, the datasets for all the chosen predictors and
outcomes are tidied and merged for modeling process and analysis.</p>
<div id="function-to-tidy-datasets" class="section level3">
<h3>Function to Tidy Datasets</h3>
<pre class="r"><code>tidy_df = function(data, variable, pivot = FALSE, average = FALSE) {
  
  if(pivot) {
    data = data |&gt;
      pivot_longer(cols = -iso3_code,
                   names_to = &quot;year&quot;,
                   values_to = variable) |&gt;
      janitor::clean_names()
  }
  
  data = data |&gt;
    mutate(year = as.numeric(year),
           iso3_code = str_replace_all(iso3_code, &quot;^GBR.*&quot;, &quot;GBR&quot;),
           iso3_code = str_replace_all(iso3_code, &quot;^IRQ.*&quot;, &quot;IRQ&quot;),
           country = countrycode(iso3_code, origin = &quot;iso3c&quot;,
                                 destination = &quot;country.name&quot;,
                                 nomatch = NA, warn = FALSE)) |&gt; 
    drop_na(country)
  
  if(average) {
    
    if(&quot;region&quot; %in% colnames(data)) {
      data = data |&gt;
        group_by( country, region, year) |&gt;
        summarize(!!variable := mean(value))
    }
    
    else {
        data = data |&gt;
          group_by(country, year) |&gt;
          summarize(!!variable := mean(value))
    }
    
  }
  
  return(data)
  
}</code></pre>
<p>We defined a function <code>tidy_df()</code>to pipe after importing
each dataset to automatically tidy the datasets. The
<code>countrycode()</code> function standardizes the country names of
each dataset since some of the country names are represented
inconsistently across dataset files. For example, South Korea was
represented as “Korea (Republic of)” and “Korea, Rep.”</p>
<p>Moreover, for the countrycode() function, NA is returned if no
matches are found and warnings are also suppressed by
<code>nomatch = NA</code> and <code>warn = FALSE</code> respectively
since some datasets include iso3 codes for entities that are not
countries. For example, EUU represents the European Union; however, the
<code>countrycode()</code> function only recognizes iso3 codes for
countries and returns a warning, but we are interested in countries and
regions. A boolean parameter called <code>pivot</code> was included to
indicate if a dataset needs to be pivoted and subsequently perform
<code>pivot_longer()</code>, since some datasets had years organized as
different columns, where each column represented values for that
year.</p>
<p>Also, some of the datasets include rates for different categories.
For example, the data for economic crime includes crime rates for fraud,
burglary and more. Therefore, another boolean parameter called
<code>average</code> was included to pass an option to group by and
summarize rates across categories and genders of different datasets, in
order to provide a standardized measure and reduce complexity for
analysis.</p>
</div>
<div id="economic-determinants" class="section level3">
<h3>Economic Determinants</h3>
<pre class="r"><code>gdp_df = 
  read_excel(path = &quot;data/worldbank/gdp.xls&quot;,
             sheet = &quot;Data&quot;, skip = 3, na = &quot;&quot;) |&gt;
  select(iso3_code = 2, &quot;2015&quot;:&quot;2023&quot;) |&gt;
  tidy_df(&quot;gdp&quot;, pivot = TRUE)

inflation_df = 
  read_excel(path = &quot;data/worldbank/inflation_rate.xls&quot;, 
             sheet = &quot;Data&quot;, skip = 3, na = &quot;&quot;) |&gt;
  select(iso3_code = 2, &quot;2015&quot;:&quot;2023&quot;) |&gt;
  tidy_df(&quot;inflation_rate&quot;, pivot = TRUE)

unemployment_df =
  read_excel(path = &quot;data/worldbank/unemployment_rate.xlsx&quot;,
             range = &quot;A1:BP437&quot;, na = &quot;..&quot;) |&gt;
  rename_with(str_replace_all, pattern = &quot; \\[.*&quot;, replacement = &quot;&quot;) |&gt;
  select(iso3_code = 4, &quot;2013&quot;:&quot;2023&quot;) |&gt;
  tidy_df(&quot;unemployment_rate&quot;, pivot = TRUE)

human_develop_df =
  read_csv(file = &quot;data/undp/human_development_index.csv&quot;, na = &quot;&quot;) |&gt;
  head(-11) |&gt;
  rename_with(str_replace_all, pattern = &quot;hdi_&quot;, replacement = &quot;&quot;) |&gt;
  select(iso3_code = 1, &quot;2015&quot;:&quot;2022&quot;) |&gt;
  tidy_df(&quot;hdi&quot;, pivot = TRUE)</code></pre>
<p>The following variables were identified as economic prdictors of
violence:</p>
<ul>
<li><code>gdp</code></li>
<li><code>inflation</code></li>
<li><code>unemployment</code></li>
<li><code>human development index</code></li>
</ul>
<p>The <code>pivot</code> parameter of the <code>tidy_df()</code>
function was set to true for these datasets, since all of them had the
different years as data columns, which needs to be pivoted
accordingly.</p>
</div>
<div id="social-determinants" class="section level3">
<h3>Social Determinants</h3>
<pre class="r"><code>econ_crime_df = 
  read_excel(path = &quot;data/unodc/corruption_economic_crime.xlsx&quot;, skip = 2) |&gt;
  janitor::clean_names() |&gt;
  filter(unit_of_measurement == &quot;Rate per 100,000 population&quot;) |&gt;
  tidy_df(&quot;economic_crime_rate&quot;,  average = TRUE)

personnel_df =
  read_excel(path = &quot;data/unodc/criminal_justice_personnel.xlsx&quot;, skip = 2) |&gt;
  janitor::clean_names() |&gt;
  filter(unit_of_measurement == &quot;Rate per 100,000 population&quot;,
         indicator == &quot;Criminal Justice Personnel&quot;, 
         sex == &quot;Total&quot;) |&gt;
  tidy_df(&quot;personnel_rate&quot;, average = TRUE)

trafficking_df =
  read_excel(path = &quot;data/unodc/human_trafficking.xlsx&quot;, skip = 2) |&gt;
  janitor::clean_names() |&gt;
  filter(indicator == &quot;Detected trafficking victims&quot;,
         category == &quot;Total&quot;, 
         sex == &quot;Total&quot;,
         age == &quot;Total&quot;,
         txt_value != &quot;&lt;5&quot;) |&gt;
  mutate(value = str_replace_all(txt_value, &quot;,&quot;, &quot;&quot;),
         value = as.numeric(value)) |&gt;
  select(iso3_code : region, year, trafficked_victims = value) |&gt;
  tidy_df(&quot;trafficked_victims&quot;)

alcohol_df =
  read_csv(file = &quot;data/who/alcohol_consumption.csv&quot;, na = &quot;&quot;) |&gt;
  janitor::clean_names() |&gt;
  filter(dim1 == &quot;Both sexes&quot;) |&gt;
  select(iso3_code = spatial_dim_value_code, 
         year = period, 
         value = fact_value_numeric) |&gt;
  tidy_df(&quot;alcohol_consumption_rate&quot;, average = TRUE)</code></pre>
<p>The following variables were identified as social prdictors of
violence:</p>
<ul>
<li><code>economic crime</code></li>
<li><code>criminal justice personnel</code></li>
<li><code>human trafficking</code></li>
<li><code>alcohol</code></li>
</ul>
<p>The datasets for economic crimes and criminal justice personnel also
provided data for both counts and rates per 100,000 people.
Subsequently, we filtered to choose rates per 100,000 people for
standardization and comparability. The human trafficking dataset
provided data for number of human trafficking victims, instead of
trafficking rates; the dataset also included a category for total number
of trafficking victims, so the data was filtered for total category and
neither the <code>pivot</code> nor <code>average</code> options were set
to true in the <code>tidy_df()</code> function.</p>
</div>
<div id="outcomes-of-violence" class="section level3">
<h3>Outcomes of Violence</h3>
<pre class="r"><code>homicide_df = 
  read_excel(path = &quot;data/unodc/intentional_homicide.xlsx&quot;, skip = 2) |&gt;
  janitor::clean_names() |&gt;
  filter(indicator == &quot;Victims of intentional homicide&quot;,
         unit_of_measurement == &quot;Rate per 100,000 population&quot;,
         dimension == &quot;Total&quot;, 
         sex == &quot;Total&quot;, 
         age == &quot;Total&quot;) |&gt;
  tidy_df(&quot;homicide_rate&quot;, average = TRUE)
  
violence_df = 
  read_excel(path = &quot;data/unodc/violent_sexual_crime.xlsx&quot;, skip = 2) |&gt;
  janitor::clean_names() |&gt;
  filter(indicator == &quot;Violent offences&quot;,
         unit_of_measurement == &quot;Rate per 100,000 population&quot;) |&gt;
  tidy_df(&quot;violence_rate&quot;, average = TRUE)</code></pre>
<p>Unlike the tidied dataset for EDA, the datasets for homicide and
violence had their respective rates averaged across category, since we
are interested in the average rates of homicide victims and violent
offences for regression analysis.</p>
</div>
<div id="merge-datasets" class="section level3">
<h3>Merge Datasets</h3>
<pre class="r"><code>merged_violence_df =
  left_join(homicide_df, violence_df) |&gt;
  left_join(gdp_df) |&gt;
  left_join(inflation_df) |&gt;
  left_join(unemployment_df) |&gt;
  left_join(human_develop_df) |&gt;
  left_join(econ_crime_df) |&gt;
  left_join(personnel_df) |&gt;
  left_join(trafficking_df) |&gt;
  left_join(alcohol_df) |&gt;
  mutate(country = as.factor(country),
         region = as.factor(region)) |&gt;
  filter(between(year, 2015, 2023)) |&gt;
  relocate(iso3_code) |&gt;
  drop_na(violence_rate, homicide_rate)

head(merged_violence_df)</code></pre>
<pre><code>## # A tibble: 6 × 14
## # Groups:   country, region [1]
##   iso3_code country region  year homicide_rate violence_rate          gdp
##   &lt;chr&gt;     &lt;fct&gt;   &lt;fct&gt;  &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;
## 1 ALB       Albania Europe  2015          2.22          5.51 11386853113.
## 2 ALB       Albania Europe  2016          2.74          4.87 11861199831.
## 3 ALB       Albania Europe  2017          2.01          4.64 13019726212.
## 4 ALB       Albania Europe  2018          2.29          4.54 15156424015.
## 5 ALB       Albania Europe  2019          2.26          5.09 15401826127.
## 6 ALB       Albania Europe  2020          2.13          4.71 15162734205.
## # ℹ 7 more variables: inflation_rate &lt;dbl&gt;, unemployment_rate &lt;dbl&gt;, hdi &lt;dbl&gt;,
## #   economic_crime_rate &lt;dbl&gt;, personnel_rate &lt;dbl&gt;, trafficked_victims &lt;dbl&gt;,
## #   alcohol_consumption_rate &lt;dbl&gt;</code></pre>
<pre class="r"><code>write.csv(merged_violence_df, file = &quot;./data/merged_violence.csv&quot;)</code></pre>
<p>The final merged dataset includes 771 rows and 14 columns, including
iso3 codes, country, region, year, homicide rate, average violence
offence rate, gdp, inflation rate, unemployment rate, average crime
rate, criminal justice personnel rate, total, human trafficking rate and
alcohol consumption rate as variables. There is a total of 127 distinct
countries.</p>
<p>After merging the datasets, country and region were converted to
categorical variables and the dataset was filtered for the years between
2015 and 2023, the period of our interest for analysis. Although the
datasets were merged with matching country names tidied by the
<code>countrycode()</code>, the iso3 codes were retained, since they are
required for plotting maps which can be found under the shiny section of
this website.</p>
</div>
</div>
</div>
<div id="exploratory-data-analysis" class="section level1">
<h1><em>Exploratory Data Analysis</em></h1>
<div id="homicide-victims" class="section level2">
<h2>Homicide Victims</h2>
<div id="global-trends-of-homicide-victims" class="section level3">
<h3>Global Trends of Homicide Victims</h3>
<pre class="r"><code>homicide_visual_df |&gt;
  group_by(region, sex, year) |&gt;
  summarize(avg_homicide_rate = mean(homicide_rate)) |&gt;
  ggplot(aes(y = avg_homicide_rate, x = year, color = sex)) +
  geom_smooth(se = FALSE) +
  facet_grid(~region) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = &quot;Year&quot;,
       y = &quot;Average Rate of Homicide Victims&quot;,
       title = &quot;Homicide Victims Worldwide&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The Americas and Asia have significantly higher average homicide rate
across years for male victims compared to the other regions. The average
homicide rate between genders are not significant for Africa, Asia and
Oceania.</p>
</div>
<div id="comparing-the-americas-and-asia" class="section level3">
<h3>Comparing the Americas and Asia</h3>
<pre class="r"><code>homicide_visual_df |&gt;
  filter(region %in% c(&quot;Asia&quot;, &quot;Americas&quot;)) |&gt;
  group_by(category, region) |&gt;
  summarize(avg_homicide_rate = mean(homicide_rate)) |&gt;
  ggplot(aes(y = avg_homicide_rate, x = region,
             fill = reorder(category, avg_homicide_rate))) +
  geom_col(position = &quot;dodge&quot;, bin = 3.0) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = &quot;Region&quot;,
       y = &quot;Average Rate of Homicide Victims&quot;,
       title = &quot;Homicide in America &amp; Asia&quot;, 
       fill = &quot;Category&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Further exploring homicide in Americas and Asia, the Americas have
higher homicide rates for most categories compared to Asia. Homicides of
perpetrator to victim relationship unknown has the largest homicide
rate. Homicides of unknown types is next category with the highest
homicide rate in the Americas.</p>
<p>On the other hand, Asia has a significantly high homicide rate in
socio-political homicide compared to the other categories,suggesting
high casualties as a result of socio-political activities for countries
in Asia. The other categories have a homicide rate lesser than 5
percent.</p>
</div>
<div id="breakdown-of-homicide" class="section level3">
<h3>Breakdown of Homicide</h3>
<pre class="r"><code>homicide_visual_df |&gt;
  group_by(category, year) |&gt;
  summarize(avg_homicide_rate = mean(homicide_rate)) |&gt;
  ggplot(aes(y = avg_homicide_rate, x = as.factor(year), fill = 
               reorder(category, avg_homicide_rate))) +
  geom_bar(stat = &quot;identity&quot;) + 
  labs(title = &quot;Distribution of Homicide by Category&quot;,
       x = &quot;Year&quot;,
       y = &quot;Total Rate of Homicide Victims&quot;,
       fill = &quot;Category&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Homicides of unknown types and perpetrator to victim relationship
unknown are two highest proportions in the total homicide rate,
indicating most homicides are committed by strangers or have no
connection with the victims. Also, we can observe that homicide rates as
a result of organized criminal groups or gangs and interpersonal
homicide are the next significant proportions in homicide. The total
homicide rate increases sharply from 2015 to 2017 compared to the other
years possibly due to socioeconomic factors, such as economic
instability.</p>
</div>
</div>
<div id="violence-offences-victims" class="section level2">
<h2>Violence: Offences &amp; Victims</h2>
<div id="global-trends-of-violent-offences" class="section level3">
<h3>Global Trends of Violent Offences</h3>
<pre class="r"><code>violence_visual_df |&gt; 
  filter(indicator == &quot;Violent offences&quot;) |&gt; 
  group_by(category, year, region) |&gt; 
  summarise(grp_mean_rate = mean(violence_rate)) |&gt; 
  ggplot(aes(x = year, y = grp_mean_rate, color = category)) +
  geom_line() +
  facet_wrap(~region, ncol=2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = &quot;bottom&quot;) + 
  labs(title = &quot;Violent Offences Worldwide&quot;,
       x = &quot;Year&quot;, 
       y = &quot;Average Rate of Violent Offences&quot;) +
  guides(color = guide_legend(nrow = 3))</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Africa’s most common violent offence category was serious assault,
with the Americas trading off between serious assault and acts intended
to induce fear or emotional distress. From 2015-2021 Oceania clearly has
the highest rates of serious assault, but it drops severely in 2022.</p>
</div>
<div id="exploring-violent-offences" class="section level3">
<h3>Exploring Violent Offences</h3>
<pre class="r"><code>violence_visual_df |&gt;
  filter(indicator == &quot;Violent offences&quot;) |&gt;
  group_by(category, year, region) |&gt; 
  summarise(avg_violence_rate = mean(violence_rate)) |&gt; 
  mutate(category = fct_reorder(category, avg_violence_rate)) |&gt;
  ggplot(aes(x = category, y = avg_violence_rate, fill = region)) +
  geom_bar(stat = &quot;identity&quot;, position = &quot;dodge&quot;) +
  facet_wrap(~year, ncol=2) +
  theme(axis.text.x = element_text(angle = 80, hjust = 1),
        legend.position = &quot;bottom&quot;) +
  labs(x = &quot;Category&quot;, 
       y = &quot;Average Rate of Violent Offences&quot;,
       title = &quot;Violent Offences by Category Across Time&quot;) </code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-7-1.png" width="768" /></p>
<p>The plot above shows similar trends to the line graph above, but
allows us to compare more closely the rates for categories that are less
visible such as sexual violence, where Oceania appears to have the
highest rates of as well. We see more clearly that with Oceania’s drop
in serious assaults in 2022, Americas and Oceania have similar
trends.</p>
</div>
<div id="victims-of-sexual-violence" class="section level3">
<h3>Victims of Sexual Violence</h3>
<p>Even in 2024, it is still ever-important to discuss sexual violence
crimes. Violence against women is a public health issue and any type of
sexual violence is a violation of human rights, harming physical,
mental, sexual, and reproductive health. We are interested in seeing
more specifically trends in sexual violence across the years for regions
with sufficient data.</p>
<pre class="r"><code>violence_visual_df |&gt;
  filter(indicator == &quot;Victims of sexual violence&quot;,
         region != &quot;Africa&quot;) |&gt;
  group_by(region, sex, year) |&gt;
  summarize(avg_victim_rate = mean(violence_rate)) |&gt;
  ggplot(aes(y = avg_victim_rate, x = year, color = sex)) +
  geom_smooth(se = FALSE) +
  facet_grid(~region) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = &quot;Year&quot;,
       y = &quot;Average Rate of Sexual Violence Victims&quot;,
       title = &quot;Sexual Violence Worldwide&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>When exploring victim rate of sexual violence, we can see that in
overall, there is a higher average victim rate for females; the largest
disparity in victim rate between the genders can be observed in Oceania,
where the rate for females have been sharply increasing over the years.
The victim rate for the Americas and Europe has also been increasing,
but steadily compared to Oceania over the years, while Asia has
experienced a decline from 2019. Africa was not included because the
data was either very small or missing for many countries in the
region.</p>
</div>
<div id="investigating-sexual-violence" class="section level3">
<h3>Investigating Sexual Violence</h3>
<pre class="r"><code>violence_visual_df |&gt;
  filter(indicator == &quot;Victims of sexual violence&quot;,
         region != &quot;Africa&quot;) |&gt;
  group_by(category, sex, region) |&gt;
  summarize(avg_victim_rate = mean(violence_rate)) |&gt;
  ggplot(aes(y = avg_victim_rate, x = region, 
             fill = reorder(category, avg_victim_rate))) +
  geom_col(position = &quot;dodge&quot;) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = &quot;Region&quot;,
       y = &quot;Average Rate of Sexual Violence Victims&quot;,
       fill = &quot;Category&quot;,
       title = &quot;Sexual Violence By Category Across Region&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Further exploring victims of sexual violence, except for perpetrator
unknown to the victim, Oceania has a higher average victim rate of
sexual violence for the all other categories compared to the other
regions. Oceania, Europe and Americas have relationship of perpetrator
is not known as the highest category for victim rate. Similar to
homicide, the perpetrators are strangers or have no connection with the
victims for most sexual violence. On the other hand, Asia has a
significantly low average victim rate, having other perpetrator known to
the victim as the category with the highest rate.</p>
</div>
<div id="breakdown-of-sexual-violence" class="section level3">
<h3>Breakdown of Sexual Violence</h3>
<pre class="r"><code>violence_visual_df |&gt;
  filter(indicator == &quot;Victims of sexual violence&quot;,
         region != &quot;Africa&quot;) |&gt;
  group_by(category, year) |&gt;
  summarize(avg_victim_rate = mean(violence_rate)) |&gt;
  ggplot(aes(y = avg_victim_rate, x = as.factor(year), 
             fill = reorder(category, avg_victim_rate))) +
  geom_bar(stat = &quot;identity&quot;) + 
  labs(x = &quot;Year&quot;,
       y = &quot;Total Rate of Sexual Violence Victims&quot;,
       title = &quot;Distribution of Sexual Violence by Category&quot;,
       fill = &quot;Category&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Relationship to perpetrator is not known in the category with a
significant proportion to total victim rate of sexual violence compared
to the other categories across the years. The proportion of victim rates
for the other three categories become approximately equal to each other
from 2019. Specifically, the proportion for intimate partner or family
member and perpetrator unknown to the victim increases over time.</p>
</div>
</div>
<div id="global-prevalence-of-violence" class="section level2">
<h2>Global Prevalence of Violence</h2>
<p>Across the time period from 2015 to 2023, the Americas consistently
exhibited a significantly higher homicide rate compared to other
regions. The difference in this region is pronounced, indicating a
persistent and widespread issue with violent crime. The homicide rate in
Asia is also notable. There was a rising trend in homicide rate from
2015 to 2021, but was followed by a sharp decrease in 2022. However, it
should be noted that not all countries that reported homicide rate also
reported the violence rate.</p>
<p>The drop in 2022 may imply that there was a potential shift or
improvement in the region, but it could also mean that there are some
missing data in that year, leading a bias or misinterpretation. When
examining violence rates, the Americas followed a similar trend to the
homicide rate, with rates significantly higher than the other regions.
This trend reflects the persistent issue of violence in the region,
affecting not only homicide rates but also broader forms of violence.
However, Oceania presented an extreme outlier in terms of victim rates
of sexual violence, surpassing even the Americas.</p>
<p>Putting these results against our own knowledge, Oceania’s rates seem
higher than expected. This raises the question of if higher rates mean
more violent countries or countries who just have reported more crimes.
It is very important to address that these outcome data are compiled by
UNODC but the data itself comes from each nation’s respective
administrative registers, often managed by law enforcement agencies.
Additionally, UNODC comes by this data not through requirement but by
the United Nations Survey of Crime Trends and Operations of Criminal
Justice Systems (UN-CTS). This means that countries voluntarily supply
their information. However, a safety-guard is that UNODC does check for
consistency and coherence with other data sources.</p>
</div>
</div>
<div id="regression" class="section level1">
<h1><em>Regression</em></h1>
<div id="background" class="section level2">
<h2>Background</h2>
<p>Our motivation for doing regression is to determine the significant
predictors of the two measures of violence: (1) homicide rate and (2)
violence rate.</p>
<p>Violence is a complex and multifaceted issue, especially when
considered in a global context. To better understand its various
dimensions, we aimed to include a diverse set of predictors that reflect
different underlying factors driving violence. Specifically, economic
indicators like GDP, inflation rate, and the Human Development Index
(HDI) capture aspects of economic inequality, which can influence social
unrest and violence. Economic crime rate, personnel rate, and number of
trafficked victims serve as indicators of the level of criminal activity
in a country, as well as potential efficacy of law enforcement. Such
indicators could be predictive of violence in the country. Lastly,
alcohol rate is included to address the possibility that substance usage
could influence the occurrence of violence.</p>
<p>Given the plausible theoretical linkage between each of our included
predictor variables and the outcome variables of interest, we seek to
develop models that can determine which factors are most predictive of
homicide and violence rate.</p>
<p>We performed this analysis to uncover the extent to which different
factors influence homicide rate and violence rate as outcomes.</p>
</div>
<div id="functions-for-fitting-data" class="section level2">
<h2>Functions for Fitting Data</h2>
<div id="best_subset" class="section level3">
<h3>Best_subset</h3>
<pre class="r"><code>best_subset = function(predictor, outcome, criterion) {
  
  optimal_subset &lt;- 
    leaps(x = predictor, y = outcome, nbest = 3, 
      method = criterion, names = names(predictor))
  
  if (criterion == &quot;Cp&quot;) {
    optimal_criterion &lt;- optimal_subset[[criterion]] %&gt;% min()
    optimal_subset_idx &lt;- optimal_subset[[criterion]] %&gt;% which.min()
    
  } else {
    optimal_criterion &lt;- optimal_subset[[criterion]] %&gt;% max()
    optimal_subset_idx &lt;- optimal_subset[[criterion]] %&gt;% which.max()
  }
  
  return(list(Criterion = optimal_criterion , 
       Variable_Selection = optimal_subset$which[optimal_subset_idx,]))
  
}</code></pre>
<p>This function serves as a wrapper around the leaps function. It
performs best-subset variable selection and then prints out the optimal
model diagnostic and the predictor variables included in the regression
model.</p>
</div>
<div id="fit_glmnet" class="section level3">
<h3>fit_glmnet</h3>
<pre class="r"><code>fit_glmnet = function(df, alpha, outcome, lambda) {
  
  outcome_formula &lt;- as.formula(paste(outcome, &quot;~.&quot;))
  predictor &lt;- model.matrix(outcome_formula, data = df)[,-1]
  predicted &lt;- df %&gt;% pull(outcome)
  
  model_fit &lt;- 
    glmnet(predictor, predicted, lambda = lambda, alpha = alpha)
  
  model_cv &lt;-
    cv.glmnet(predictor, predicted, lambda = lambda, alpha = alpha)
  
  lambda_opt = model_cv[[&quot;lambda.min&quot;]]
  
  model_fit &lt;-
    glmnet(predictor, predicted, lambda = lambda_opt, alpha = alpha)
  
  return(model_fit)
  
}</code></pre>
<p>This function serves as a wrapper for the glmnet fitting processing
and covers both the fitting and cross-validation process. It returns the
glmnet object produced after fitting with optimal lambda value.</p>
</div>
<div id="rmse_glmnet" class="section level3">
<h3>rmse_glmnet</h3>
<pre class="r"><code>rmse_glmnet = function(model, test, outcome) {
  outcome_formula &lt;- as.formula(paste(outcome, &quot;~.&quot;))
  predictor &lt;- model.matrix(outcome_formula, data = test)[,-1]
  predictions &lt;- predict.glmnet(model, model[[&quot;lambda&quot;]], newx = predictor,
                               type = &quot;response&quot;)
  
  predictions &lt;- as.vector(predictions)
  observed &lt;- test %&gt;% 
    pull(outcome)
  
  return(caret::RMSE(predictions, observed))
  
}</code></pre>
<p>This is a wrapper function for the glmnet prediction and evaluation
process. Given a fitted glmnet model, a test dataset, and an outcome
variable of interest, this function predicts the avlues in the test
dataset and then calculates and returns the rmse.</p>
</div>
<div id="check_model" class="section level3">
<h3>check_model</h3>
<pre class="r"><code>check_model = function(data, name) {
  
  diagnostics = list()
  
  resid_fit =
    data |&gt;
    ggplot(aes(y = resid, x = pred)) +
    geom_point() +
    geom_smooth(method = &quot;lm&quot;) + 
    labs(title = name,
         y = &quot;Residual&quot;, 
         x = &quot;Fitted Value&quot;)

  qqplot = 
    data |&gt;
      filter(is.finite(resid)) |&gt;
      ggplot(aes(sample = resid)) +
      stat_qq() +
      stat_qq_line(col = &quot;red&quot;) +
      xlab(&quot;Theoretical Quantiles&quot;) +
      ylab(&quot;Residuals&quot;) +
      ggtitle(name)
  
  qqnorm(pull(data, resid), main = &quot;QQ Plot of Residuals&quot;)
  qqline(pull(data, resid), col = &quot;red&quot;)
      
  diagnostics = append(diagnostics, list(qqplot, resid_fit))
  patchwork::wrap_plots(diagnostics)
}</code></pre>
<p>This is a plotting function to combine several different plot types
that assess the assumptions of linear models</p>
</div>
</div>
<div id="descriptive-statistics" class="section level2">
<h2>Descriptive Statistics</h2>
<div id="visualizations-of-distributions" class="section level3">
<h3>Visualizations of Distributions</h3>
<p><img src="p8105_fp_report_files/figure-html/distributions-1.png" width="1920" /></p>
<p>Distribution of all variables were checked and it was found that they
are all right-skewed, except for human development index. HDI variable
showed bimodal and slightly left-skewed distribution. Hence, we decided
to apply ln transformations and Box-Cox transformations to these
variables in order to account for concerns regarding the constancy of
variance in linear models. Transformations are intended to approximately
normalize the data.</p>
</div>
<div id="data-transformations" class="section level3">
<h3>Data Transformations</h3>
<div id="natural-log-transform" class="section level4">
<h4>Natural Log Transform</h4>
<pre class="r"><code>ln_transform = function(value) {
  return(log(abs(value)))
}

ln_df = 
  merged_violence_df |&gt;
  mutate(across(c(homicide_rate:alcohol_consumption_rate), 
                ln_transform))

ln_df |&gt;
  select(homicide_rate:alcohol_consumption_rate) |&gt;
  ggpairs()</code></pre>
<p><img src="p8105_fp_report_files/figure-html/ln-transform-1.png" width="1920" /></p>
</div>
<div id="box-cox-transform" class="section level4">
<h4>Box-Cox Transform</h4>
<pre class="r"><code>boxcox_transform = function(value) {
  if (all(is.na(value))) {
    return(value) 
  }

  min_value = min(value, na.rm = TRUE) 
  if (min_value &lt;= 0) {
    value = value + abs(min_value) + 0.00001  
  }

  if (length(unique(value)) == 1) {
    return(value) 
  }

  boxcox_result = MASS::boxcox(value ~ 1, plotit = FALSE)
  lambda = boxcox_result$x[which.max(boxcox_result$y)]  

  if(lambda != 0) {
    transformed_value = (value^lambda - 1) / lambda
  } else {
    transformed_value = log(value)
  }
  return(transformed_value)
}

boxcox_df = merged_violence_df |&gt; 
  mutate(across(c(homicide_rate:alcohol_consumption_rate), 
                ~ boxcox_transform(.)))

boxcox_df |&gt;
  select(homicide_rate:alcohol_consumption_rate) |&gt;
  ggpairs()</code></pre>
<p><img src="p8105_fp_report_files/figure-html/boxcox-1.png" width="1920" /></p>
<p>Though the transformations were expected to improve the normality,
the results suggest that the transformations are not necessarily
effective. In fact, we found that the original data already provides a
reasonable representation of the underlying distribution.</p>
<p>While the natural logarithm helped with normality, the Box-Cox
transformation did not substantially improve the data’s distribution.
Box-Cox transformation requires shifting data to be strictly positive,
which could introduce unnecessary complexity.</p>
<p>Since neither transformation substantially approved the shapes of the
distributions, we ultimately decided to use the original data. Concerns
regarding the normality of the distributions are alleviated by the
Central Limit Theorem. With a sufficiently large amount of data points,
we can assume that the sampling distribution is approximately normal.
Using the convention that n &gt; 30 allows for the assumption of
approximate normality, our 310 observation dataset suffices to be
supported by Central Limit Theorem (CLT).</p>
</div>
</div>
<div id="multicolliniearity-diagnostics" class="section level3">
<h3>Multicolliniearity Diagnostics</h3>
<p>We used <code>cor()</code> to find the correlation between the eight
predictors of homicide rate and violence.</p>
<pre class="r"><code>cor_matrix = 
  cor(merged_violence_df[, c(&quot;gdp&quot;, &quot;inflation_rate&quot;, &quot;unemployment_rate&quot;, &quot;hdi&quot;,
                             &quot;economic_crime_rate&quot;, &quot;personnel_rate&quot;, &quot;trafficked_victims&quot;, 
                             &quot;alcohol_consumption_rate&quot;)], use = &quot;pairwise.complete.obs&quot;)

ggcorrplot(cor_matrix, 
           method = &quot;circle&quot;,  
           type = &quot;lower&quot;,  
           lab = TRUE,        
           lab_size = 3,      
           colors = c(&quot;blue&quot;, &quot;white&quot;, &quot;red&quot;), # Color scale (blue = negative, red = positive)
           title = &quot;Correlation Heatmap&quot;
)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>There is moderate correlation between <code>hdi</code> and
<code>alcohol_consumption_rate</code>, corr = 0.56, and moderately high
correlation between <code>trafficked_victims</code> and
<code>gdp</code>, corr = 0.77.</p>
</div>
</div>
<div id="data-pre-processing" class="section level2">
<h2>Data Pre-Processing</h2>
<div id="define-lambda-range" class="section level3">
<h3>Define Lambda Range</h3>
<pre class="r"><code>lambda = 10^(seq(-2, 2.75, 0.1))</code></pre>
</div>
<div id="approach-to-pre-processing-data" class="section level3">
<h3>Approach to Pre-Processing Data</h3>
<p>Prior to performing any model fitting, we split our intial dataset
into separate homicide and violence datasets, each of which includes the
outcome variable and all numeric predictor variables. Specific predictor
and outcome dataframes, and an outcome matrix, are created for later use
in linear models, as well as lasso.</p>
<div id="pre-processing-for-homicide" class="section level4">
<h4>Pre-Processing for Homicide</h4>
<pre class="r"><code>homicide_df =
  merged_violence_df |&gt; 
  ungroup() |&gt; 
  select(
    homicide_rate, everything(), -violence_rate, -year, -country, -region, 
    -iso3_code) |&gt; 
  drop_na()

homicide_matrix &lt;- model.matrix(homicide_rate ~., data = homicide_df)[,-1]

homicide_predictors &lt;- homicide_df %&gt;% 
  select(-homicide_rate)

homicide_outcome &lt;- homicide_df %&gt;% 
  pull(homicide_rate)</code></pre>
</div>
<div id="pre-processing-for-violence" class="section level4">
<h4>Pre-Processing for Violence</h4>
<pre class="r"><code>violence_df =
  merged_violence_df |&gt; 
  ungroup() |&gt; 
  select(
    violence_rate, everything(), -year, -homicide_rate, -country, -region, 
    -iso3_code) |&gt;
  drop_na()

violence_matrix &lt;- model.matrix(violence_rate ~., data = violence_df)[,-1]
  
violence_predictors &lt;- violence_df %&gt;% 
  select(-violence_rate)

violence_outcome &lt;- violence_df %&gt;% 
  pull(violence_rate)</code></pre>
</div>
</div>
</div>
<div id="baseline-mlr-with-additive-effects" class="section level2">
<h2>Baseline MLR with Additive Effects</h2>
<p>First, we decided to fit a baseline MLR with additive effects from
all possible predictor variables to use as a point of reference for our
modeling process. This step provides basic understanding of the extent
to which different covariates contribute to the outcomes of
interest.</p>
<div id="predict-homicide-rates" class="section level3">
<h3>Predict Homicide Rates</h3>
<pre class="r"><code>baseline_MLR_hom &lt;- lm(homicide_rate ~ gdp + inflation_rate + unemployment_rate +
                   hdi + economic_crime_rate + personnel_rate + trafficked_victims + 
                    alcohol_consumption_rate , data = merged_violence_df)

baseline_MLR_hom_fitted &lt;- baseline_MLR_hom[[&quot;fitted.values&quot;]]

baseline_MLR_hom %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="36%" />
<col width="17%" />
<col width="14%" />
<col width="16%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">77.1223904</td>
<td align="right">6.8949976</td>
<td align="right">11.1852672</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">gdp</td>
<td align="right">0.0000000</td>
<td align="right">0.0000000</td>
<td align="right">1.4401126</td>
<td align="right">0.1508748</td>
</tr>
<tr class="odd">
<td align="left">inflation_rate</td>
<td align="right">-0.7310164</td>
<td align="right">0.1997345</td>
<td align="right">-3.6599403</td>
<td align="right">0.0002978</td>
</tr>
<tr class="even">
<td align="left">unemployment_rate</td>
<td align="right">-0.3801340</td>
<td align="right">0.1437800</td>
<td align="right">-2.6438594</td>
<td align="right">0.0086262</td>
</tr>
<tr class="odd">
<td align="left">hdi</td>
<td align="right">-79.7616365</td>
<td align="right">9.3579304</td>
<td align="right">-8.5234270</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">economic_crime_rate</td>
<td align="right">0.0047858</td>
<td align="right">0.0037406</td>
<td align="right">1.2793927</td>
<td align="right">0.2017441</td>
</tr>
<tr class="odd">
<td align="left">personnel_rate</td>
<td align="right">0.0090816</td>
<td align="right">0.0064515</td>
<td align="right">1.4076778</td>
<td align="right">0.1602584</td>
</tr>
<tr class="even">
<td align="left">trafficked_victims</td>
<td align="right">-0.0004297</td>
<td align="right">0.0005839</td>
<td align="right">-0.7358718</td>
<td align="right">0.4623817</td>
</tr>
<tr class="odd">
<td align="left">alcohol_consumption_rate</td>
<td align="right">-0.2165605</td>
<td align="right">0.2052374</td>
<td align="right">-1.0551708</td>
<td align="right">0.2921934</td>
</tr>
</tbody>
</table>
<p>Results from baseline MLR show that that inflation rate, unemployment
rate and hdi are significant predictors of homicide rate at alpha =
0.05.</p>
</div>
<div id="collinearity-of-baseline-homicide-model"
class="section level3">
<h3>Collinearity of Baseline Homicide Model</h3>
<pre class="r"><code>vif_baseline_hom_MLR &lt;- car::vif(baseline_MLR_hom)
vif_baseline_hom_MLR %&gt;% 
  tibble(
    variable = names(vif_baseline_hom_MLR),
    VIF = vif_baseline_hom_MLR
  ) %&gt;% 
  select(variable, VIF) %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gdp</td>
<td align="right">2.396884</td>
</tr>
<tr class="even">
<td align="left">inflation_rate</td>
<td align="right">1.176607</td>
</tr>
<tr class="odd">
<td align="left">unemployment_rate</td>
<td align="right">1.164411</td>
</tr>
<tr class="even">
<td align="left">hdi</td>
<td align="right">2.455203</td>
</tr>
<tr class="odd">
<td align="left">economic_crime_rate</td>
<td align="right">1.700020</td>
</tr>
<tr class="even">
<td align="left">personnel_rate</td>
<td align="right">1.306548</td>
</tr>
<tr class="odd">
<td align="left">trafficked_victims</td>
<td align="right">2.315171</td>
</tr>
<tr class="even">
<td align="left">alcohol_consumption_rate</td>
<td align="right">1.896571</td>
</tr>
</tbody>
</table>
<p>Results from VIF show that there is no multicollinearity issue (VIF
&lt; 5).</p>
</div>
<div id="predict-violence-rates" class="section level3">
<h3>Predict Violence Rates</h3>
<pre class="r"><code>baseline_MLR_viol &lt;- lm(violence_rate ~ gdp + inflation_rate + unemployment_rate +
                   hdi + economic_crime_rate + personnel_rate + trafficked_victims + 
                    alcohol_consumption_rate , data = merged_violence_df)

baseline_MLR_viol_fitted &lt;- baseline_MLR_viol[[&quot;fitted.values&quot;]]

baseline_MLR_viol %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="36%" />
<col width="17%" />
<col width="15%" />
<col width="15%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">44.2045930</td>
<td align="right">19.9655911</td>
<td align="right">2.2140388</td>
<td align="right">0.0275754</td>
</tr>
<tr class="even">
<td align="left">gdp</td>
<td align="right">0.0000000</td>
<td align="right">0.0000000</td>
<td align="right">2.7199674</td>
<td align="right">0.0069083</td>
</tr>
<tr class="odd">
<td align="left">inflation_rate</td>
<td align="right">-2.0163975</td>
<td align="right">0.5783639</td>
<td align="right">-3.4863818</td>
<td align="right">0.0005625</td>
</tr>
<tr class="even">
<td align="left">unemployment_rate</td>
<td align="right">-0.1171670</td>
<td align="right">0.4163384</td>
<td align="right">-0.2814226</td>
<td align="right">0.7785796</td>
</tr>
<tr class="odd">
<td align="left">hdi</td>
<td align="right">-12.9837171</td>
<td align="right">27.0974152</td>
<td align="right">-0.4791497</td>
<td align="right">0.6321801</td>
</tr>
<tr class="even">
<td align="left">economic_crime_rate</td>
<td align="right">0.1193201</td>
<td align="right">0.0108316</td>
<td align="right">11.0158771</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">personnel_rate</td>
<td align="right">-0.0628082</td>
<td align="right">0.0186813</td>
<td align="right">-3.3620841</td>
<td align="right">0.0008735</td>
</tr>
<tr class="even">
<td align="left">trafficked_victims</td>
<td align="right">0.0082359</td>
<td align="right">0.0016908</td>
<td align="right">4.8709129</td>
<td align="right">0.0000018</td>
</tr>
<tr class="odd">
<td align="left">alcohol_consumption_rate</td>
<td align="right">-1.6323824</td>
<td align="right">0.5942983</td>
<td align="right">-2.7467389</td>
<td align="right">0.0063817</td>
</tr>
</tbody>
</table>
<p>Results from MLR show that gdp, inflation rate, crime rate, personnel
rate, number of trafficked victims per 100,000 and alcohol consumption
rates are significant predictors of violence rate at significance level
alpha = 0.01.</p>
</div>
<div id="collinearity-of-baseline-violence-model"
class="section level3">
<h3>Collinearity of Baseline Violence Model</h3>
<pre class="r"><code>vif_baseline_viol_MLR &lt;- car::vif(baseline_MLR_viol)
vif_baseline_viol_MLR %&gt;% 
  tibble(
    variable = names(vif_baseline_viol_MLR),
    VIF = vif_baseline_viol_MLR
  ) %&gt;% 
  select(variable, VIF) %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gdp</td>
<td align="right">2.396884</td>
</tr>
<tr class="even">
<td align="left">inflation_rate</td>
<td align="right">1.176607</td>
</tr>
<tr class="odd">
<td align="left">unemployment_rate</td>
<td align="right">1.164411</td>
</tr>
<tr class="even">
<td align="left">hdi</td>
<td align="right">2.455203</td>
</tr>
<tr class="odd">
<td align="left">economic_crime_rate</td>
<td align="right">1.700020</td>
</tr>
<tr class="even">
<td align="left">personnel_rate</td>
<td align="right">1.306548</td>
</tr>
<tr class="odd">
<td align="left">trafficked_victims</td>
<td align="right">2.315171</td>
</tr>
<tr class="even">
<td align="left">alcohol_consumption_rate</td>
<td align="right">1.896571</td>
</tr>
</tbody>
</table>
<p>Results from VIF show that there is no multicollinearity issue (VIF
&lt; 5).</p>
</div>
</div>
<div id="lasso" class="section level2">
<h2>Lasso</h2>
<p>We used lasso to as a feature selection tool to find the most
important variables in predicting homicide rate and violence rate.</p>
<div id="predictors-for-violence-rate" class="section level3">
<h3>Predictors for Violence Rate</h3>
<pre class="r"><code>lasso_violence_fit = 
  glmnet(violence_matrix, violence_outcome, lambda = lambda)

lasso_violence_cv = 
  cv.glmnet(violence_matrix, violence_outcome, lambda = lambda)

lambda_violence_opt = 
  lasso_violence_cv[[&quot;lambda.min&quot;]]

lasso_violence_fit = 
  glmnet(violence_matrix, violence_outcome, lambda = lambda_violence_opt)

lasso_violence_fit |&gt; 
  broom::tidy() |&gt; 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">step</th>
<th align="right">estimate</th>
<th align="right">lambda</th>
<th align="right">dev.ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">1</td>
<td align="right">33.2327610</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="even">
<td align="left">gdp</td>
<td align="right">1</td>
<td align="right">0.0000000</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="odd">
<td align="left">inflation_rate</td>
<td align="right">1</td>
<td align="right">-1.7615771</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="even">
<td align="left">unemployment_rate</td>
<td align="right">1</td>
<td align="right">-0.0409621</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="odd">
<td align="left">hdi</td>
<td align="right">1</td>
<td align="right">-1.7103106</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="even">
<td align="left">economic_crime_rate</td>
<td align="right">1</td>
<td align="right">0.1133362</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="odd">
<td align="left">personnel_rate</td>
<td align="right">1</td>
<td align="right">-0.0548232</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="even">
<td align="left">trafficked_victims</td>
<td align="right">1</td>
<td align="right">0.0080624</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
<tr class="odd">
<td align="left">alcohol_consumption_rate</td>
<td align="right">1</td>
<td align="right">-1.5437306</td>
<td align="right">0.3981072</td>
<td align="right">0.5192427</td>
</tr>
</tbody>
</table>
<pre class="r"><code>lasso_predict_violence &lt;- 
  predict.glmnet(lasso_violence_fit, lambda_violence_opt, 
                 newx = violence_matrix, type = &quot;response&quot;)
  
lasso_predict_violence &lt;- as.vector(lasso_predict_violence)

lasso_violence_resid &lt;- tibble(
  residuals = violence_outcome - lasso_predict_violence
)</code></pre>
<p>The optimal lambda for violence rate is 0.3981072. Based on lasso
estimates, the coefficient for <code>gdp</code> was shrunk to 0.</p>
</div>
<div id="predictors-for-homicide-rate" class="section level3">
<h3>Predictors for Homicide Rate</h3>
<pre class="r"><code>lasso_homicide_fit = 
  glmnet(homicide_matrix, homicide_outcome, lambda = lambda)

lasso_homicide_cv = 
  cv.glmnet(homicide_matrix, homicide_outcome, lambda = lambda)

lambda_homicide_opt = 
  lasso_homicide_cv[[&quot;lambda.min&quot;]]

lasso_homicide_fit = 
  glmnet(homicide_matrix, homicide_outcome, lambda = lambda_homicide_opt)

lasso_homicide_fit |&gt; 
  broom::tidy() |&gt; 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">step</th>
<th align="right">estimate</th>
<th align="right">lambda</th>
<th align="right">dev.ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">1</td>
<td align="right">75.5833480</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="even">
<td align="left">gdp</td>
<td align="right">1</td>
<td align="right">0.0000000</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="odd">
<td align="left">inflation_rate</td>
<td align="right">1</td>
<td align="right">-0.6907875</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="even">
<td align="left">unemployment_rate</td>
<td align="right">1</td>
<td align="right">-0.3553263</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="odd">
<td align="left">hdi</td>
<td align="right">1</td>
<td align="right">-78.2143914</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="even">
<td align="left">economic_crime_rate</td>
<td align="right">1</td>
<td align="right">0.0043479</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="odd">
<td align="left">personnel_rate</td>
<td align="right">1</td>
<td align="right">0.0085533</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="even">
<td align="left">trafficked_victims</td>
<td align="right">1</td>
<td align="right">-0.0002459</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
<tr class="odd">
<td align="left">alcohol_consumption_rate</td>
<td align="right">1</td>
<td align="right">-0.2056343</td>
<td align="right">0.0630957</td>
<td align="right">0.3524531</td>
</tr>
</tbody>
</table>
<pre class="r"><code>lasso_predict_homicide &lt;- 
  predict.glmnet(lasso_homicide_fit, lambda_homicide_opt, 
                 newx = homicide_matrix, type = &quot;response&quot;)
  
lasso_predict_homicide &lt;- as.vector(lasso_predict_homicide)

lasso_homicide_resid &lt;- tibble(
  residuals = homicide_outcome - lasso_predict_homicide
)</code></pre>
<p>The optimal lambda for homicide rate is 0.0630957. Similar to the
results from violence, the coefficient for <code>gdp</code> was shrunk
to 0.</p>
</div>
</div>
<div id="criterion-based-procedure" class="section level2">
<h2>Criterion-Based Procedure</h2>
<div id="best-subset-regression-for-violence" class="section level3">
<h3>Best-Subset Regression for Violence</h3>
<div id="predict-violence-rate-with-r-squared" class="section level4">
<h4>Predict Violence Rate with R-Squared</h4>
<pre class="r"><code>violence_best_subset_rsq &lt;- 
  best_subset(predictor = violence_predictors, outcome = violence_outcome, 
              criterion = &quot;adjr2&quot;)

violence_best_subset_rsq</code></pre>
<pre><code>## $Criterion
## [1] 0.5103599
## 
## $Variable_Selection
##                      gdp           inflation_rate        unemployment_rate 
##                     TRUE                     TRUE                    FALSE 
##                      hdi      economic_crime_rate           personnel_rate 
##                    FALSE                     TRUE                     TRUE 
##       trafficked_victims alcohol_consumption_rate 
##                     TRUE                     TRUE</code></pre>
</div>
<div id="predict-violence-rate-with-cp" class="section level4">
<h4>Predict Violence Rate with Cp</h4>
<pre class="r"><code>violence_best_subset_Cp &lt;- 
  best_subset(predictor = violence_predictors, outcome = violence_outcome, 
              criterion = &quot;Cp&quot;)
violence_best_subset_Cp</code></pre>
<pre><code>## $Criterion
## [1] 5.363491
## 
## $Variable_Selection
##                      gdp           inflation_rate        unemployment_rate 
##                     TRUE                     TRUE                    FALSE 
##                      hdi      economic_crime_rate           personnel_rate 
##                    FALSE                     TRUE                     TRUE 
##       trafficked_victims alcohol_consumption_rate 
##                     TRUE                     TRUE</code></pre>
</div>
<div id="collinearity-of-best-subset-violence-model"
class="section level4">
<h4>Collinearity of Best-Subset Violence Model</h4>
<pre class="r"><code>subset_violence_lm &lt;- lm(violence_rate ~ gdp + inflation_rate + 
                           economic_crime_rate + personnel_rate + trafficked_victims +
                           alcohol_consumption_rate, data = violence_df)

subset_violence_fitted &lt;- subset_violence_lm[[&quot;fitted.values&quot;]]


vif_subset_violence_model &lt;- car::vif(subset_violence_lm) 

vif_subset_violence_model %&gt;% 
  tibble(
    variable = names(vif_subset_violence_model),
    VIF = vif_subset_violence_model
  ) %&gt;% 
  select(variable, VIF) %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gdp</td>
<td align="right">2.346184</td>
</tr>
<tr class="even">
<td align="left">inflation_rate</td>
<td align="right">1.070415</td>
</tr>
<tr class="odd">
<td align="left">economic_crime_rate</td>
<td align="right">1.373276</td>
</tr>
<tr class="even">
<td align="left">personnel_rate</td>
<td align="right">1.240083</td>
</tr>
<tr class="odd">
<td align="left">trafficked_victims</td>
<td align="right">2.282920</td>
</tr>
<tr class="even">
<td align="left">alcohol_consumption_rate</td>
<td align="right">1.168675</td>
</tr>
</tbody>
</table>
<p>All variables have VIF value below 5, suggesting that there is no
multi-colinearity concerns.</p>
</div>
<div id="interpretation" class="section level4">
<h4>Interpretation</h4>
<p>The results from criterion-based procedures suggest that significant
predictors for violence_rate are gdp, inflation_rate,
economic_crime_rate, personnel_rate, trafficked_victims and
alcohol_consumption rate, with a total of 6 predictors. This yields the
most appropriate Cp value (5.363), which is approximately close to the
number of predictors, and highest adjusted R-squared (0.510).</p>
</div>
</div>
<div id="best-subset-regression-for-homicide" class="section level3">
<h3>Best Subset Regression for Homicide</h3>
<div id="predict-homicide-rate-with-r-squared" class="section level4">
<h4>Predict Homicide Rate with R-Squared</h4>
<pre class="r"><code>homicide_best_subset_rsq &lt;- 
  best_subset(predictor = homicide_predictors, outcome = homicide_outcome, 
              criterion = &quot;adjr2&quot;)

homicide_best_subset_rsq</code></pre>
<pre><code>## $Criterion
## [1] 0.3367418
## 
## $Variable_Selection
##                      gdp           inflation_rate        unemployment_rate 
##                     TRUE                     TRUE                     TRUE 
##                      hdi      economic_crime_rate           personnel_rate 
##                     TRUE                     TRUE                     TRUE 
##       trafficked_victims alcohol_consumption_rate 
##                    FALSE                     TRUE</code></pre>
</div>
<div id="predict-homicide-rate-with-cp" class="section level4">
<h4>Predict Homicide Rate with Cp</h4>
<pre class="r"><code>homicide_best_subset_Cp &lt;- 
  best_subset(predictor = homicide_predictors, outcome = homicide_outcome, 
              criterion = &quot;Cp&quot;)

homicide_best_subset_Cp</code></pre>
<pre><code>## $Criterion
## [1] 6.511243
## 
## $Variable_Selection
##                      gdp           inflation_rate        unemployment_rate 
##                    FALSE                     TRUE                     TRUE 
##                      hdi      economic_crime_rate           personnel_rate 
##                     TRUE                     TRUE                    FALSE 
##       trafficked_victims alcohol_consumption_rate 
##                    FALSE                    FALSE</code></pre>
</div>
<div id="collinearity-of-best-subset-homicide-model"
class="section level4">
<h4>Collinearity of Best-Subset Homicide Model</h4>
<pre class="r"><code>subset_homicide_lm &lt;- lm(homicide_rate ~ inflation_rate + unemployment_rate +
                           hdi + economic_crime_rate, data = homicide_df)

subset_homicide_fitted &lt;- subset_homicide_lm[[&quot;fitted.values&quot;]]


vif_subset_homicide_model &lt;- car::vif(subset_homicide_lm)
vif_subset_homicide_model %&gt;% 
  tibble(
    variable = names(vif_subset_homicide_model),
    VIF = vif_subset_homicide_model
  ) %&gt;% 
  select(variable, VIF) %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">inflation_rate</td>
<td align="right">1.169288</td>
</tr>
<tr class="even">
<td align="left">unemployment_rate</td>
<td align="right">1.034265</td>
</tr>
<tr class="odd">
<td align="left">hdi</td>
<td align="right">1.468355</td>
</tr>
<tr class="even">
<td align="left">economic_crime_rate</td>
<td align="right">1.316883</td>
</tr>
</tbody>
</table>
<p>All variables have VIF value below 5, suggesting that there is no
multi-colinearity concerns.</p>
</div>
<div id="interpretation-1" class="section level4">
<h4>Interpretation</h4>
<p>For homicide_rate, the results are not as straightforward. The best
model based on Cp and R-squared seems to be the model with 4 predictors
because it has the lowest Cp (6.36), and a relatively high adjusted
R-squared (0.331), indicating a good balance between fit and complexity.
As more predictors are added, R-squared adjusts slightly but Cp levels
off at around 6 predictors. The model with 4 predictors, which includes
inflation_rate, unemployment_rate, hdi, personnel_rate, seems to be a
better trade-off.</p>
</div>
</div>
</div>
<div id="model-comparison" class="section level2">
<h2>Model Comparison</h2>
<div id="create-training-and-testing-datasets" class="section level3">
<h3>Create Training and Testing Datasets</h3>
<pre class="r"><code>cv_df_violence &lt;- 
  modelr::crossv_mc(violence_df, 100)

cv_df_violence &lt;- cv_df_violence %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )

cv_df_homicide &lt;-
  modelr::crossv_mc(homicide_df, 100)

cv_df_homicide &lt;- cv_df_homicide %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )</code></pre>
</div>
<div id="fit-models" class="section level3">
<h3>Fit Models</h3>
<div id="violence" class="section level4">
<h4>Violence</h4>
<pre class="r"><code>cv_df_violence &lt;-
  cv_df_violence %&gt;% 
  mutate(
    MLR_all_var = map(train, \(df) lm(violence_rate ~ ., data = df)),
    MLR_best_subset = map(train, \(df) lm(violence_rate ~ gdp + inflation_rate + 
                           economic_crime_rate + personnel_rate + trafficked_victims +
                           alcohol_consumption_rate, data = df)),
    lasso = map(train, \(df) fit_glmnet(df, outcome = &quot;violence_rate&quot;, 
                                        alpha = 1,lambda = lambda))
  ) %&gt;% 
  mutate(
    rmse_all_var = map2_dbl(
      MLR_all_var, test, \(mod, test) rmse(model = mod, data = test)),
    rmse_best_subset = map2_dbl(
      MLR_best_subset, test, \(mod, test) rmse(model = mod, data = test)),
    rmse_lasso = map2_dbl(
      lasso, test, \(mod, test) rmse_glmnet(mod, test, &quot;violence_rate&quot;))
  ) %&gt;% 
  select(starts_with(&quot;rmse_&quot;))</code></pre>
</div>
<div id="homicide" class="section level4">
<h4>Homicide</h4>
<pre class="r"><code>cv_df_homicide &lt;-
  cv_df_homicide %&gt;% 
  mutate(
    MLR_all_var = map(train, \(df) lm(homicide_rate ~ ., data = df)),
    MLR_best_subset = map(train, \(df) lm(homicide_rate ~ inflation_rate 
                          + unemployment_rate + hdi + economic_crime_rate, data = df)),
    lasso = map(train, \(df) fit_glmnet(df, outcome = &quot;homicide_rate&quot;, 
                                        alpha = 1,lambda = lambda))
  ) %&gt;% 
  mutate(
    rmse_all_var = map2_dbl(
      MLR_all_var, test, \(mod, test) rmse(model = mod, data = test)),
    rmse_best_subset = map2_dbl(
      MLR_best_subset, test, \(mod, test) rmse(model = mod, data = test)),
    rmse_lasso = map2_dbl(
      lasso, test, \(mod, test) rmse_glmnet(mod, test, &quot;homicide_rate&quot;))
  ) %&gt;% 
  select(starts_with(&quot;rmse_&quot;))</code></pre>
</div>
</div>
<div id="comparing-the-rmse" class="section level3">
<h3>Comparing the RMSE</h3>
<div id="violence-1" class="section level4">
<h4>Violence</h4>
<pre class="r"><code>cv_df_violence %&gt;%
  pivot_longer(
    everything(),
    names_to = &quot;Model&quot;, 
    values_to = &quot;RMSE&quot;,
    names_prefix = &quot;rmse_&quot;
  ) %&gt;% 
  mutate(
    Model = fct_inorder(Model)
  ) %&gt;% 
  ggplot(aes(x = Model, y = RMSE)) +
  geom_violin() +
  ggtitle(&quot;RMSE by Model for Predicting Violence Rate&quot;) +
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>Examining the distribution of RMSEs for each of the 3 models for
predicting violence rate, we see that they are relatively similar. It
appears that the MLR including all predictor variables has greater
spread than the other two distributions, as it has a higher upper bound
in the violin plot.</p>
<p>The similarity in performance among all 3 models likely relates to
the few number of predictor variables that exist in our studied dataset.
In general, each of the 3 models will not differ by many predictor
variables, and therefore perform similarly. Comparing the 3 models, the
best subset regression model may be considered optimal as it reduces
model complexity, without the further caveat of difficulty interpreting
beta coefficients, as is the case with lasso models.</p>
</div>
<div id="homicide-1" class="section level4">
<h4>Homicide</h4>
<pre class="r"><code>cv_df_homicide %&gt;%
  pivot_longer(
    everything(),
    names_to = &quot;Model&quot;, 
    values_to = &quot;RMSE&quot;,
    names_prefix = &quot;rmse_&quot;
  )%&gt;% 
  mutate(
    Model = fct_inorder(Model)
  ) %&gt;% 
  ggplot(aes(x = Model, y = RMSE)) +
  geom_violin() +
  ggtitle(&quot;RMSE by Model for Predicting Homicide Rate&quot;) +
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Examining the 3 models we used to predict homicide rate, we see that
the distribution of RMSE across 100-fold cross-validation are nearly
identical. This is likely in regard to the few predictor variables
included in our dataset. In particular, with such few predictor
variables, lasso is likely not the most well-suited for this task, as
there is not a serious need to reduce model complexity. Consequently,
the number of variables included in each of the 3 models is quite
similar, and the difference of 1 or 2 included predictors between each
of the models does not produce a substantial change in model
effectiveness. Comparing the 3 models, the best subset regression model
may be considered the best as it reduces model complexity but maintains
ease of interpretability of beta coefficients.</p>
</div>
</div>
</div>
<div id="model-diagnostics" class="section level2">
<h2>Model Diagnostics</h2>
<div id="all-variables-included-mlr" class="section level3">
<h3>All Variables included MLR</h3>
<pre class="r"><code>baseline_hom_resid_df = 
  merged_violence_df |&gt;
  add_residuals(baseline_MLR_hom) |&gt;
  add_predictions(baseline_MLR_hom) 

baseline_viol_resid_df = 
  merged_violence_df |&gt;
  add_residuals(baseline_MLR_viol) |&gt;
  add_predictions(baseline_MLR_viol) 

check_model(baseline_hom_resid_df, &quot;MLR All Predictors Homicide Rate&quot;) </code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-36-1.png" width="672" /><img src="p8105_fp_report_files/figure-html/unnamed-chunk-36-2.png" width="672" /></p>
<pre class="r"><code>check_model(baseline_viol_resid_df, &quot;MLR All Predictors Violence Rate&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-36-3.png" width="672" /><img src="p8105_fp_report_files/figure-html/unnamed-chunk-36-4.png" width="672" />
Examining the QQ-plots for the MLRs with all predictor variables
included, we notice that our assumption of normality of residuals may be
in violation, as there appear to many lower-bound and upper-bound
outliers that do not fall along the reference line. Regarding the plots
of fitted values versus residuals, we see differing results based on
whether homicide rate or violence rate is the outcome variable. With
homicide as the outcome variable, we can see residuals oscillate above
and below the reference line, indicating approximate linearity of the
relationship between the predictors and the outcome variables. However,
the greater variability in the residuals as fitted values increase,
suggests that we are seeing heteroscedasticity. Regarding violence rate
as the outcome variable, we see both issues with heteroscedasticity and
linearity.</p>
</div>
<div id="best-subset-mlr" class="section level3">
<h3>Best Subset MLR</h3>
<pre class="r"><code>subset_homicide_resid_df = 
  merged_violence_df |&gt;
  add_residuals(subset_homicide_lm) |&gt;
  add_predictions(subset_homicide_lm) 

subset_violence_resid_df = 
  merged_violence_df |&gt;
  add_residuals(subset_violence_lm) |&gt;
  add_predictions(subset_violence_lm) 

check_model(subset_homicide_resid_df, &quot;MLR Best-Subset Homicide Rate&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-37-1.png" width="672" /><img src="p8105_fp_report_files/figure-html/unnamed-chunk-37-2.png" width="672" /></p>
<pre class="r"><code>check_model(subset_violence_resid_df, &quot;MLR Best-Subset Violence Rate&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/unnamed-chunk-37-3.png" width="672" /><img src="p8105_fp_report_files/figure-html/unnamed-chunk-37-4.png" width="672" /></p>
<p>Examining the QQ-plots for the MLRs using the best-subset of
predictor variables, we once again notice that our assumption of
normality of residuals may be in violation, as there appear to many
lower-bound and upper-bound outliers that do not fall along the
reference line. For the fitted versus residuals plot for homicide rate,
we see violations of both linearity and homosecdascity. The equivalent
plot for violence rate presents similar concerns regarding
homoscedascity, but shows a greater spread of residuals along the
horizontal reference line, and therefore better implies linearity of
relationship between predictor variables and outcome.</p>
</div>
<div id="lasso-1" class="section level3">
<h3>Lasso</h3>
<pre class="r"><code>lasso_homicide_resid_df =
  lasso_homicide_resid |&gt; 
  pull(residuals) |&gt;
  bind_cols(lasso_predict_homicide) |&gt;
  rename(resid = &quot;...1&quot;, pred = &quot;...2&quot;)

lasso_violence_resid_df =
  lasso_violence_resid |&gt; 
  pull(residuals) |&gt;
  bind_cols(lasso_predict_violence) |&gt;
  rename(resid = &quot;...1&quot;, pred = &quot;...2&quot;)

check_model(lasso_homicide_resid_df, &quot;Lasso Homicide Rate&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/warning-FALSE-1.png" width="672" /><img src="p8105_fp_report_files/figure-html/warning-FALSE-2.png" width="672" /></p>
<pre class="r"><code>check_model(lasso_violence_resid_df, &quot;Lasso Violence Rate&quot;)</code></pre>
<p><img src="p8105_fp_report_files/figure-html/warning-FALSE-3.png" width="672" /><img src="p8105_fp_report_files/figure-html/warning-FALSE-4.png" width="672" /></p>
<p>Consistent with results from the QQ-plots of the previous two MLR
models, lasso models for both homicide rate and violence rate show
potential violations of the assumption of normality, as many lower-bound
and upper-bound outlier residuals do not fall along the reference line.
For the fitted versus residuals plot of homicide rate, we see possible
heteroscedascity, while the equivalent plot for homicide rate shows both
possible heteroscedascity and non-linearity.</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Based on our comparisons of RMSE, we can conclude that our
best-subset regression models are most accurate at predicting the
outcomes: (1) Violence Rate and (2) Homicide Rate.</p>
<p>The best-subset regression model for predicting violence rate yielded
an adjusted r-squared of and included the following variables a
predictors: GDP, inflation rate, crime rate, personnel rate, trafficked
victims, and alcohol consumption rate. The best-subset regression model
for predicting homicide rate returned an r-squared of . The variables
included in this model were inflation rate, unemployment rate, HDI, and
crime rate.</p>
<p>Despite moderately high R-squared values for each of these models, we
must acknowledge that the models’ performance and accuracy may suffer
from certain drawbacks. In particular, model diagnostics revealed
concerns regarding the normality, linearity, and homoscedascity of the
dataset used to produce these models. Additionally, transformations
applied to cope with the concerns regarding normality failed to produce
more normalized distributions for any of the predictor variables. As a
result, the R-squared values for our models may be inaccurate and
different forms of modelling, such as a non-linear approach, may be
better suited for exploring what variables predict violence and homicide
rates.</p>
</div>
</div>
<div id="citation" class="section level1">
<h1><em>Citation</em></h1>
<ul>
<li>UNODC (2024), UNODC Research - Data Portal – Access and functioning
of justice. <a href="https://dataunodc.un.org/dp-cjs-persons-convicted"
class="uri">https://dataunodc.un.org/dp-cjs-persons-convicted</a>
(Accessed on Nov. 2024).</li>
<li>UNODC (2024), UNODC Research - Data Portal – Corruption and Economic
Crime. <a href="https://dataunodc.un.org/dp-crime-corruption-offences"
class="uri">https://dataunodc.un.org/dp-crime-corruption-offences</a>
(Accessed on Nov. 2024).</li>
<li>UNODC (2024), UNODC Research - Data Portal - Violent and Sexual
Crime. <a href="https://dataunodc.un.org/dp-crime-violent-offences"
class="uri">https://dataunodc.un.org/dp-crime-violent-offences</a>
(Accessed on Nov. 2024)</li>
</ul>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
