---
title: "viz"
author: "Malika Top"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(plotly)
```

```{r}
merged_violence_df |> 
  plot_ly(x = ~as.factor(year), y = ~violence_rate, color = ~country,
          type = 'scatter', mode = 'lines', colors = "viridis",
          line = list(width = 1)) |> 
  layout(title = "Violence Rates Across Years", xaxis = list(title = "Year"),
         yaxis = list(title = "Rate (per 100,000 population)"))
```

```{r}
merged_violence_df |> 
  plot_ly(x = ~as.factor(year), y = ~homicide_rate, color = ~country,
          type = 'scatter', mode = 'lines', colors = "viridis",
          line = list(width = 1)) |> 
  layout(title = "Homicide Rates Across Years", xaxis = list(title = "Year"),
         yaxis = list(title = "Rate (per 100,000 population)"))
```

```{r}
merged_violence_df |> 
  plot_ly(x = ~violence_rate, y = ~homicide_rate, size = ~gdp,
          text = ~paste('Country', country, '<br>Year:', year, '<br>HDI:', hdi,
                        '<br>GDP:', gdp), 
          type = 'scatter', mode = 'markers', color = ~region,
          marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2, color = '#FFFFFF')))
```

```{r}
offence_plot = 
  simple_violent_offences_df |> 
  group_by(category, year, country, region) |> 
  summarise(grp_mean_rate = mean(violence_rate)) |> 
  ggplot(aes(x = category, y = grp_mean_rate, fill = region)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~year, ncol=2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
offence_plot  

```















