---
title: "Violence Trend by Country"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(flexdashboard)
library(viridis)
library(shiny)

merged_violence_df = 
  read.csv("./data/merged_violence.csv")[-1] |> 
  pivot_longer(
    cols = c(homicide_rate:violence_rate), 
    names_to = "outcome", 
    values_to = "rate", 
    names_pattern = "(.*)_rate"
  ) 
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
region_choices = 
  merged_violence_df |>
  distinct(region) |>
  pull(region) |>
  sort()

region_choices = c("Total", region_choices)

selectInput(
  inputId = "region_choice", 
  label = h3("Select Region"), 
  choices = region_choices, 
  selected = "Total"
)
```

```{r}
outcome_choices = 
  merged_violence_df |>
  distinct(outcome) |>
  pull(outcome)

radioButtons(
  inputId = "outcome_choice", 
  label = h3("Select Outcome Type"), 
  choices = outcome_choices,
  selected = "homicide"
)
```

Column 
-----------------------------------------------------------------------

### Outcome Rates Across Years per Region 

```{r}
renderPlotly(
  merged_violence_df |> 
    filter(
      if (input[["region_choice"]] == "Total") TRUE 
      else region == input[["region_choice"]],
      outcome == input[["outcome_choice"]]
      ) |>
    mutate(rate = round(rate, digits = 3), 
           text_label = str_c("Country: ", country, 
                              "\nYear: ", year,
                              "\nRate: ", rate)
           ) |>
    group_by(country) |>
    plot_ly(x = ~as.factor(year), 
            y = ~rate, 
            color = ~country,
            type = 'scatter', 
            mode = 'lines', 
            line = list(width = 1), 
            text = ~text_label, 
            hovertemplate = paste("%{text}<extra></extra>")
            ) |> 
    layout(xaxis = list(title = "Year"),
          yaxis = list(title = "Rate (per 100,000 population)"))
)
```

