---
title: "Interactive Map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(viridis)
library(shiny)
```

```{r include=FALSE}
merged_violence_outcome = 
  read.csv("./data/merged_violence.csv")[-1] |> 
  pivot_longer(
    cols = c(homicide_rate:violence_rate), 
    names_to = "outcome", 
    values_to = "rate", 
    names_pattern = "(.*)_rate"
  )
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
region_choices = 
  merged_violence_outcome |>
  distinct(region) |>
  pull(region) |>
  sort()

region_choices = c("Total", region_choices)

selectInput(
  inputId = "region_choice", 
  label = h3("Select Region"), 
  choices = region_choices, 
  selected = "Total"
)
```


```{r}
outcome_choices = 
  merged_violence_outcome |>
  distinct(outcome) |>
  pull(outcome)

radioButtons(
  inputId = "outcome_choice", 
  label = h3("Select Outcome Type"), 
  choices = outcome_choices,
  selected = "homicide"
)
```


```{r}
year_choices = 
  merged_violence_outcome |>
  distinct(year) |> 
  pull(year)

sliderInput(
  inputId = "year_range", 
  label = h3("Select Year Range"), 
  min = 2015, 
  max = 2023, 
  value = c(2020, 2022),
  sep = ""
)
```


Column {data-width=500}
-----------------------------------------------------------------------

### Global Visualization 

```{r}
renderPlotly(
  merged_violence_outcome |>
    filter(
      if (input[["region_choice"]] == "Total") TRUE 
      else region == input[["region_choice"]],
      outcome == input[["outcome_choice"]],
      year %in% input[["year_range"]][1]:input[["year_range"]][2]
      ) |>
    group_by(country, iso3_code) |>
    summarize(avg_rate = mean(rate)) |> 
    mutate(avg_rate = round(avg_rate, digits = 3),
           text_label = str_c("Country: ", country, 
                              "\nAvg Rate: ", avg_rate)) |>
    plot_ly(type = 'choropleth', 
          locations = ~iso3_code, 
          z = ~avg_rate, 
          text = ~text_label, 
          hovertemplate = paste("%{text}<extra></extra>"))
)
```



Column {data-width=500}
-----------------------------------------------------------------------

### Average Outcome Rate per Region over the Selected Year

```{r}
renderPlotly(
  merged_violence_outcome |>
    filter(
      if (input[["region_choice"]] == "Total") TRUE 
      else region == input[["region_choice"]],
      outcome == input[["outcome_choice"]]
    ) |>
    group_by(country) |>
    summarize(avg_rate = mean(rate)) |>
    mutate(country = fct_reorder(country, avg_rate)) |>
    plot_ly(x = ~country, y = ~avg_rate, color = ~country,type = "bar") |>
    layout(xaxis = list(title = "Country"), 
           yaxis = list(title = "Average rate over the selected year")
         )
  )
```




